name: Run Regression

on:
  push:
    branches:
      - feature/run-regression

jobs:
    run-regression:
        name: Run Regression
        runs-on: ubuntu-latest
        # name: Run Manual Regression on: workflow_dispatch: inputs: name: choice: drop down with dev or qa
        steps:
          - name: Checkout Regression Code
            uses: actions/checkout@v3
            with:
              repository: 'serenaandlily/sl-testing-automation'
              ref: main  # locally it's on Develop. TODO: check running on main
              token: ${{ secrets.GITHUB_AUTOMATION_TOKEN }}
              path: 'sl-testing-automation'
          
          - name: Set up JDK 11
            uses: actions/setup-java@v2
            with:
              distribution: 'adopt'
              java-version: '11'
    
          - name: Configure Environment
            run: cp src/config/env/env_base_github_secrets.json src/config/env/env_base.json
    
          - name: Run Regression Suite
            run: mvn -Dsurefire.rerunFailingTestsCount=2 test -DsuitePath=suites/panel/regression.xml