name: Release Pipeline

on:
  push:
    branches:
      - main
      - feature/* # add condition 
      - fix/*

env:
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    env:
        CI: true
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Setup and cache node modules
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'npm'
            cache-dependency-path: package-lock.json
            registry-url: 'https://npm.pkg.github.com'
            #scope: '@serenaandlily'
        
        - name: npm install project dependencies
          run: npm install
        
        - name: Install Vercel CLI
          run: npm install vercel
            
        - name: Run unit tests
          run: npm test 
  
  # test auto-rebase against main. fail build if rebase conflict occurs

  deploy-develop:
    name: Deploy Develop
    runs-on: ubuntu-latest
    needs: run-unit-tests
    if: success() # Only deploy if tests passed
    env:
      name: develop
    steps:
      - name: Deploy to Develop
        run: echo "Deploying to the Develop environment."
      
      - name: Pull Vercell environment variables
        run: npx vercel pull --yes --environment=preview --git-branch=develop --token $VERCEL_TOKEN
      
      - name: Run Vercel build
        run: npx vercel build --token $VERCEL_TOKEN
      
      - name: Deploy to Vercel
        run: npx vercel deploy --prebuilt --token $VERCEL_TOKEN
  

  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: deploy-develop
    if: success()
    env:
      name: production
    steps:
      - name: Deploy to Production
        run: echo "Deploying to the Production environment."
      
      - name: Pull Vercell environment variables
        run: npx vercel pull --yes --environment=production --token $VERCEL_TOKEN
      
      - name: Run Vercel build
        run: npx vercel build --prod --token $VERCEL_TOKEN
      
      - name: Deploy to Vercel
        run: npx vercel deploy --prebuilt --prod --token $VERCEL_TOKEN

 