name: Release Pipeline

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*

#env:
#    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    env:
        CI: true
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16
            registry-url: 'https://npm.pkg.github.com'
            scope: '@serenaandlily'
        - name: npm install and build
          run: |
            npm install
            npm run build --if-present
            npm test
  
  deploy-develop:
    name: Deploy Develop
    runs-on: ubuntu-latest
    needs: run-unit-tests
    if: success() # Only deploy if tests passed
    env:
      name: develop
    steps:
      - name: Deploy to Develop
        run: |
          echo "Deploying to the Develop environment."
          echo "Develop secret is: ${{ secrets.DEVELOP_TEST_KEY }}"
 
  deploy-qa:
    name: Deploy QA
    runs-on: ubuntu-latest
    needs: deploy-develop
    env:
      name: qa
    steps:
      - name: Deploy to QA
        run: |
          echo "Deploying to the QA environment."
          echo "QA secret is: ${{ secrets.QA_TEST_KEY }}"