name: Manual Approval

on:
  push:
    tags:
      - 'fe-*-*-*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        #default: 'mw-pipeline'
        default: 'main'

env:
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    VERCEL_STAGING_DOMAIN: serenaandlily-nextjs-staging.vercel.app
    STAGING_TEST: cicd-test-deploy-staging.vercel.app

jobs:
  wait-for-approval:
    name: Wait for Manual Approval
    runs-on: ubuntu-latest
    #needs: deploy-staging
    steps:
      - name: Upload approval request
        run: echo "Approval request created." > approval.txt
        
      - name: Upload Approval Request
        uses: actions/upload-artifact@v3
        with:
          name: approval-request
          path: approval.txt

      - name: Check for approval
        id: check_approval
        run: |
          if [ -f approval-accepted.txt ]; then
            echo "Approval granted."
            echo "::set-output name=approved::true"
          else
            echo "Approval not granted."
            echo "::set-output name=approved::false"
          fi
        continue-on-error: false

  revert-deployment:
    name: Revert Deployment
    runs-on: ubuntu-latest
    needs: wait-for-approval
    if: ${{ needs.wait-for-approval.outputs.approved == 'false' }}
    steps:
      - name: Revert last deployment
        run: |
          echo "Reverting last deployment."
          # Add revert logic here, such as resetting the git commit or running a Vercel rollback command.